// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.DT = (function() {

    function DT() {
      var _this = this;
      this.showNext = function() {
        return DT.prototype.showNext.apply(_this, arguments);
      };
      this.getSite = function() {
        return DT.prototype.getSite.apply(_this, arguments);
      };
      this.imagePath = '/images/';
      this.remoteURLs = URLs;
      this.images = images;
      this.remoteSites = [];
    }

    DT.prototype.getDuration = function(min, max) {
      if (min == null) {
        min = 0;
      }
      if (max == null) {
        max = 10;
      }
      return Math.floor(Math.random() * (max * 1000)) + (min * 1000);
    };

    DT.prototype.getSite = function() {
      var siteIndex;
      siteIndex = Math.floor(Math.random() * this.remoteURLs.length);
      if (!this.remoteSites[siteIndex]) {
        this.remoteSites[siteIndex] = this.fetch(this.remoteURLs[siteIndex]);
      }
      return this.remoteSites[siteIndex];
    };

    DT.prototype.fetch = function(url) {
      return $.getJSON('http://pipes.yahoo.com/pipes/pipe.run?_callback=?', {
        url: url,
        _id: '4b4d3ea82bfcdbe9b6daca620fc989d3',
        _render: 'json'
      });
    };

    DT.prototype.showNext = function() {
      var _this = this;
      return this.getSite().done(function(response) {
        var $el, _ref, _ref1;
        if (((_ref = response.value.items[0]) != null ? _ref.content : void 0) != null) {
          $el = $("<a class='site' href='" + ((_ref1 = response.value.items[0]) != null ? _ref1.url : void 0) + "'/>").html($('<div />').html(response.value.items[0].content).jrumble({
            x: Math.floor(Math.random() * 3),
            y: Math.floor(Math.random() * 3),
            rotation: 0,
            speed: Math.random() * 10,
            opacity: true,
            opacityMin: Math.random()
          }).trigger('startRumble'));
          $el.css({
            "top": "" + (100 - (Math.random() * 200)) + "%",
            "left": "" + (100 - (Math.random() * 200)) + "%",
            "right": "" + (100 - (Math.random() * 200)) + "%"
          }).animate({
            "right": "" + (Math.random() * 50) + "%"
          }, _this.getDuration(0.001, 1, 'linear'));
          $('body').css('background-image', "url(" + _this.imagePath + _this.images[Math.floor(Math.random() * _this.images.length)] + ")").append($el);
          setTimeout(function() {
            return $el.remove();
          }, _this.getDuration(0.5, 2));
          return setTimeout(dt.showNext, _this.getDuration(0, 1));
        } else {
          return dt.showNext();
        }
      });
    };

    return DT;

  })();

  $(function() {
    window.dt = new DT();
    $('#contact').jrumble({
      x: 0,
      y: 0,
      rotation: 0.05,
      speed: 10,
      opacity: true
    }).trigger('startRumble');
    return dt.showNext();
  });

}).call(this);
